name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main
      - kowshik
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install & Build
        run: |
          cd kowshik-code
          npm install
          npm run build
          touch dist/.nojekyll

      - name: Deploy to gh-pages Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./kowshik-code/dist
